### ISSUE TITLE
Why Flag shoud not include dashes?

### ISSUE THREAD

**Issue by uaex** [Subito-it/Bariloche#1]
cocoapods command line contains `allow-root` and `no-ansi` 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/13354302/133713632-a2769206-a0e5-4b14-a689-e58309d0fb8e.png">

my project requires a flag named 'no-clean' for compatibility

**Comment by tcamin** [comment]
Thanks for the report, I pushed a fix to master that should allow long names with dashes.
