### ISSUE TITLE
strict command chain

### ISSUE THREAD

**Issue by uaex** [Subito-it/Bariloche#2]
for example:

```
class FooCommand: Command {
    var name: String? = "foo"
    
    var path = Argument<String>(name: "path", kind: .positional, optional: true)
    
    let subcommands : [Command] = [BarCommand()]
    
    func run() -> Bool {
        print("exec foo \(path.value ?? "<NULL>")")
        return true
    }
}

class BarCommand: Command {
    var name: String? = "bar"
    
    func run() -> Bool {
        print("exec bar")
        return true
    }
}

class HubCommand: Command {
    let subcommands : [Command] = [FooCommand()]
    
    func run() -> Bool {
        print("exec hub")
        return true
    }
}

let parser = Bariloche(command: HubCommand())
let result = parser.parse()

```

exec `tool foo bar`
result
```
exec hub
exec foo <NULL>
exec bar
```
I think it should not exec function `run` in HubCommand and FooCommand  when BarCommand hits.

If argument `path` is not optional
result
```
exec hub
Options:

    -h, --help     Show help banner of specified command


Missing required arguments `path`
```

so I think there is only one activated command:
`tool foo bar` => BarCommand is activated
`tool foo <path>` => FooCommand is activated

**Comment by uaex** [comment]
It seems that the func `run() -> Bool` is a validator, can we rename it to `validate() -> Bool`?

the activated command 's `run() -> Void` can be called by manual after `parser.parse()`

@tcamin

**Comment by tcamin** [comment]
As per documentation `Command.run()` executes a command when it is correctly parsed, so this method actually should contain the business logic for the specific command. You are not expected to call the commands manually. 

For nested commands like `myprogram mycommand --par1 --par2 mysubcommand --mysubpar1=aa  mysubsubcommand` you should expect that after executing parser.parse() the `MyCommand.run()` is invoked first followed by `MySubCommand.run()` and `MySubSubCommand.run()` if your return true in all of them.

In an example like the previous the implementation of `MyCommand.run()` and `MySubCommand.run()` will probably just contain a `return true` or a simple validation wrt to the parameters passed to them (passing --par1 and --par2 might not be valid). If for example `MyCommand.run()` returns false parsing stops.

In a certain sense `run()` does also validation, but it is mainly intended to contain the business logic. 

Hope this makes sense

**Comment by uaex** [comment]
@tcamin
in `myprogram mycommand --par1 --par2 mysubcommand --mysubpar1=aa`
I think `mysubcommand` will be parsed as positional argument, but not a subcommand.
Usually presented like `myprogram cmd0 cmd1 cmd2 --cmd2part1=aa`, only cmd2 is activated in this chain

`Command.run` is nothing serious.

In an example like `pod --version install`, --version will be parsed as a flag in subcmd `install`, not pod(as root cmd)
```
[!] Unknown option: `--version`
Did you mean: --verbose?

Usage:

    $ pod install

      Downloads all dependencies defined in `Podfile` and creates an Xcode Pods
      library project in `./Pods`.
      ...
```
 probably all arguments and flags belongs to the tail subcommand? 🤔

**Comment by tcamin** [comment]
Sorry for the late reply, as mentioned in my previous post `run()` parses and executes per command.

See the following example

```
import Bariloche

class SomeCommand: Command {
    let subcommands: [Command] = [SomeSubCommand()]
    let a1 = Argument<String>(name: "arg", kind: .named(short: nil, long: "arg1"), optional: true, help: nil)
    
    func run() -> Bool {
        print("Running command with arg1: \(a1.value!)")
        return true
    }
}

class SomeSubCommand: Command {
    let name: String? = "subcommand"
    let subcommands: [Command] = [SomeSubSubCommand()]
    let a2 = Argument<String>(name: "arg", kind: .named(short: nil, long: "arg2"), optional: true, help: nil)

    func run() -> Bool {
        print("Running command with arg2: \(a2.value!)")
        return true
    }
}

class SomeSubSubCommand: Command {
    let name: String? = "subsubcommand"
    let a3 = Argument<String>(name: "arg", kind: .named(short: nil, long: "arg3"), optional: true, help: nil)

    func run() -> Bool {
        print("Running command with arg3: \(a3.value!)")
        return true
    }
}

let parser = Bariloche(command: SomeCommand())
let result = parser.parse()
```

Running `./mycommand --arg1=1 subcommand --arg2=2 subsubcommand --arg3=3` will print

```
Running command with arg1: 1
Running command with arg2: 2
Running command with arg3: 3
Program ended with exit code: 0
```

Each command will parse it's own flags/arguments.

Using positional arguments on a command that has subcommand won't work.
